### ISSUE TITLE
Install Fail?

### ISSUE THREAD

**Issue by SolarAquarion** [elementary/icons#618]
[0/1] Installing files.
Installing subdir /home/solaraquarion/build/elementary-icon-theme-git/src/elementary-icon-theme/actions to /home/solaraquarion/build/elementary-icon-theme-git/pkg/elementary-icon-theme-git/usr/share/icons/elementary/actions
Traceback (most recent call last):
  File "/usr/bin/meson", line 26, in <module>
    sys.exit(main())
  File "/usr/bin/meson", line 23, in main
    return mesonmain.run(sys.argv[1:], launcher)
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 321, in run
    sys.exit(run_script_command(args[1:]))
  File "/usr/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 270, in run_script_command
    return cmdfunc(cmdargs)
  File "/usr/lib/python3.6/site-packages/mesonbuild/scripts/meson_install.py", line 431, in run
    do_install(log_dir, datafilename)
  File "/usr/lib/python3.6/site-packages/mesonbuild/scripts/meson_install.py", line 244, in do_install
    install_subdirs(d) # Must be first, because it needs to delete the old subtree.
  File "/usr/lib/python3.6/site-packages/mesonbuild/scripts/meson_install.py", line 266, in install_subdirs
    do_copydir(d, src_dir, full_dst_dir, exclude)
  File "/usr/lib/python3.6/site-packages/mesonbuild/scripts/meson_install.py", line 215, in do_copydir
    sanitize_permissions(abs_dst, data.install_umask)
  File "/usr/lib/python3.6/site-packages/mesonbuild/scripts/meson_install.py", line 62, in sanitize_permissions
    new_perms = 0o777 if is_executable(path) else 0o666
  File "/usr/lib/python3.6/site-packages/mesonbuild/scripts/meson_install.py", line 57, in is_executable
    return bool(os.stat(path).st_mode & 0o111)
FileNotFoundError: [Errno 2] No such file or directory: '/home/solaraquarion/build/elementary-icon-theme-git/pkg/elementary-icon-theme-git/usr/share/icons/elementary/actions/symbolic/media-skip-backward-symbolic-rtl.svg'
FAILED: meson-install 
/bin/python /usr/bin/meson --internal install /home/solaraquarion/build/elementary-icon-theme-git/src/build/meson-private/install.dat
ninja: build stopped: subcommand failed.

**Comment by ryonakano** [comment]
Closing this is an old issue and I can't confirm it.
